# Generated by Django 4.2.1 on 2023-05-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.AddField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(blank=True, upload_to="photos/categories"),
        ),
    ]
